name: Build and Test

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  gcc:
    name: GCC
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CI_COMPILER: gcc
      CI_LINKER: ${{ matrix.linker }}

    strategy:
      fail-fast: false
      matrix:
        linker: [ld, lld]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: source

      - name: Setup CMake
        id: cmake
        uses: chuckatkins/github-utils/actions/setup-cmake@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_dir: source

      - name: Update
        run: source/scripts/ci/github/run.sh update

      - name: Configure
        run: source/scripts/ci/github/run.sh configure

      - name: Build
        run: source/scripts/ci/github/run.sh build

      - name: Test
        run: source/scripts/ci/github/run.sh test

      - name: Done
        if: always()
        run: source/scripts/ci/github/run.sh done

  clang:
    name: Clang
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CI_COMPILER: clang
      CI_STDLIB: ${{ matrix.stdlib }}
      CI_RTLIB: ${{ matrix.rtlib }}
      CI_LINKER: ${{ matrix.linker }}

    strategy:
      fail-fast: false
      matrix:
        stdlib: [libstdc++, libc++]
        rtlib: [libgcc, compiler-rt]
        linker: [ld, lld]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: source

      - name: Setup CMake
        id: cmake
        uses: chuckatkins/github-utils/actions/setup-cmake@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_dir: source

      - name: Configure
        run: source/scripts/ci/github/run.sh update configure

      - name: Build
        run: source/scripts/ci/github/run.sh build

      - name: Test
        run: source/scripts/ci/github/run.sh test

      - name: Done
        if: always()
        run: source/scripts/ci/github/run.sh done
