name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changed-files:
    if: false
    name: Changed Files
    uses: ./.github/workflows/changed-files.yml

  build-and-test:
    needs: changed-files
    if: needs.changed-files.outputs.src_test

    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CMAKE_GENERATOR: Ninja
      CI_COMPILER: ${{ matrix.compiler }}
      CI_STDLIB: ${{ matrix.compiler.stdlib }}
      CI_RTLIB: ${{ matrix.compiler.rtlib }}
      CI_LINKER: ${{ matrix.linker }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        stdlib: [libstdc++, libc++]
        rtlib: [libgcc, compiler-rt]
        linker: [ld, lld]
        exclude:
          - compiler: gcc
            stdlib: libc++
          - compiler: gcc
            rtlib: compiler-rt

    steps:
      - name: Checkout code into source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Configure
        run: cmake -S source -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

  linters:
    #needs: changed-files
    #if: needs.changed-files.outputs.src || needs.changed-files.outputs.linters
    name: Linter
    uses: ./.github/workflows/linters.yml

  static-analyzers:
    needs: changed-files
    if: needs.changed-files.outputs.src
    name: Static Analyzers
    uses: ./.github/workflows/static-analyzers.yml
    permissions:
      security-events: write
