name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  changed-files:
    name: Changed Files
    uses: ./.github/workflows/changed-files.yml

  build-and-test:
    needs: changed-files
    if: needs.changed-files.outputs.src_test
    name: Build
    runs-on: ubuntu-latest
    env:
      CMAKE_GENERATOR: Ninja
      CC: ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang' }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CXXFLAGS: ${{ matrix.libcxx && format('-stdlib={0}', matrix.libcxx) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
          - compiler: clang
            libcxx: libstdc++
          - compiler: clang
            libcxx: libc++

    steps:
      - name: Checkout code into source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Install dependencies
        run: sudo -E source/scripts/ci/gha/install-dependencies.sh

      - name: Configure
        run: cmake -S source -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

  linters:
    needs: changed-files
    if: needs.changed-files.outputs.src || needs.changed-files.outputs.linters
    name: Linter
    uses: ./.github/workflows/linters.yml

  static-analyzers:
    needs: changed-files
    if: needs.changed-files.outputs.src
    name: Static Analyzers
    uses: ./.github/workflows/static-analyzers.yml
    permissions:
      security-events: write
