name: Linters

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CMAKE_GENERATOR: Ninja
      CC: clang
      CXX: clang++

    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, clang-tidy, iwyu]

    steps:
      - name: Checkout code into source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Configure
        run: |
          linter_args=()
          if [[ ${{ matrix.linter }} == cppcheck ]]
          then
            linter_args+=( -DCLANG_TIDY_EXECUTABLE=IGNORE )
            linter_args+=( -DINCLUDE_WHAT_YOU_USE_EXECUTABLE=IGNORE )
          elif [[ ${{ matrix.linter }} == clang-tidy ]]
          then
            linter_args+=( -DCPPCHECK_EXECUTABLE=IGNORE )
            linter_args+=( -DINCLUDE_WHAT_YOU_USE_EXECUTABLE=IGNORE )
          elif [[ ${{ matrix.linter }} == iwyu ]]
          then
            linter_args+=( -DCPPCHECK_EXECUTABLE=IGNORE )
            linter_args+=( -DCLANG_TIDY_EXECUTABLE=IGNORE )
          fi
          cmake \
            -S source \
            -B build \
            -DAUTOCOMPAT_ENABLE_OVERRIDE_LAUNCHER=ON \
            -DAUTOCOMPAT_ENABLE_TESTING=OFF \
            -DAUTOCOMPAT_ENABLE_LINTERS=ON \
            "${linter_args[@]}"

      - name: Build
        env:
          LAUNCHER_OVERRIDE_CC: /bin/true
          LAUNCHER_OVERRIDE_CXX: /bin/true
        run: cmake --build build
