name: Linters

on:
  workflow_call:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      CMAKE_GENERATOR: Ninja
      CC: clang
      CXX: clang++
      EXTRA_PACKAGES: ${{ matrix.linter }}
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, clang-tidy, iwyu]

    steps:
      - name: Checkout code into source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Install dependencies
        run: sudo -E source/scripts/ci/gha/install-dependencies.sh

      - name: Configure
        run: |
          linter_args=()
          if [ "${{ matrix.linter }}" == "cppcheck" ]; then
            linter_args+=( -DCLANG_TIDY_EXECUTABLE=IGNORE )
            linter_args+=( -DINCLUDE_WHAT_YOU_USE_EXECUTABLE=IGNORE )
          elif [ "${{ matrix.linter }}" == "clang-tidy" ]; then
            linter_args+=( -DCPPCHECK_EXECUTABLE=IGNORE )
            linter_args+=( -DINCLUDE_WHAT_YOU_USE_EXECUTABLE=IGNORE )
          elif [ "${{ matrix.linter }}" == "iwyu" ]; then
            linter_args+=( -DCPPCHECK_EXECUTABLE=IGNORE )
            linter_args+=( -DCLANG_TIDY_EXECUTABLE=IGNORE )
          fi
          cmake \
            -S source \
            -B build \
            -DBUILD_TESTING=OFF \
            -DAUTOCOMPAT_ENABLE_LINTERS=ON \
            "${linter_args[@]}"

      - name: Build
        run: cmake --build build
