name: Linters

on:
  workflow_call:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      CMAKE_GENERATOR: Ninja
      CC: clang
      CXX: clang++
      EXTRA_PACKAGES: ${{ matrix.linter }}
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, clang-tidy, iwyu]

    steps:
      - name: Checkout code into source directory
        uses: actions/checkout@v4
        with:
          path: source

      - name: Install dependencies
        run: sudo -E source/scripts/ci/gha/install-dependencies.sh

      - name: Configure
        run: |
          cmake \
            -S source \
            -B build \
            -DAUTOCOMPAT_ENABLE_OVERRIDE_LAUNCHER=ON \
            -DAUTOCOMPAT_ENABLE_TESTING=OFF \
            -DAUTOCOMPAT_ENABLE_LINTERS=ON

      - name: Build
        env:
          LAUNCHER_OVERRIDE_CC: /bin/true
          LAUNCHER_OVERRIDE_CXX: /bin/true
        run: cmake --build build
