name: Linters

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CC: clang
      CXX: clang++
      CI_COMPILER: clang
      CI_LINTER: ${{ matrix.linter }}

    strategy:
      fail-fast: false
      matrix:
        linter: [clang-tidy]
        #linter: [cppcheck, clang-tidy, iwyu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: source

      - name: Setup CMake
        id: cmake
        uses: chuckatkins/github-utils/actions/setup-cmake@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure
        run: |
          linter_args=()
          if [[ ${{ matrix.linter }} == cppcheck ]]
          then
              linter_args+=( CLANG_TIDY_EXECUTABLE:FILEPATH=IGNORE )
              linter_args+=( INCLUDE_WHAT_YOU_USE_EXECUTABLE:FILEPATH=IGNORE )
          elif [[ ${{ matrix.linter }} == clang-tidy ]]
          then
              linter_args+=( CPPCHECK_EXECUTABLE:FILEPATH=IGNORE )
              linter_args+=( INCLUDE_WHAT_YOU_USE_EXECUTABLE:FILEPATH=IGNORE )
          elif [[ ${{ matrix.linter }} == iwyu ]]
          then
              linter_args+=( CPPCHECK_EXECUTABLE:FILEPATH=IGNORE )
              linter_args+=( CLANG_TIDY_EXECUTABLE:FILEPATH=IGNORE )
          fi
          source/scripts/ci/github/run.sh update configure -Ddashboard_do_submit=FALSE \
              AUTOCOMPAT_ENABLE_OVERRIDE_LAUNCHER:BOOL=ON \
              AUTOCOMPAT_ENABLE_TESTING:BOOL=OFF \
              AUTOCOMPAT_ENABLE_LINTERS:BOOL=ON \
              "${linter_args[@]}"

      - name: Build
        env:
          LAUNCHER_OVERRIDE_CC: /bin/true
          LAUNCHER_OVERRIDE_CXX: /bin/true
        run: source/scripts/ci/github/run.sh build -Ddashboard_do_submit=FALSE

      - name: Done
        run: source/scripts/ci/github/run.sh done -Ddashboard_do_submit=FALSE

      - name: Summarize
        if: always()
        uses: chuckatkins/github-utils/actions/ctest-build-summary@add-ctest-build-summary
        with:
          format: tidy
