name: Static Analyzers

on:
  workflow_call:

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake

      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c-cpp
          build-mode: manual
          queries: security-extended,security-and-quality

      - run: |
          cmake \
            -S ${GITHUB_WORKSPACE} \
            -B ${GITHUB_WORKSPACE}/build \
            -DBUILD_TESTING=OFF

          # We don't need to actually do a build since CodeQL just needs the
          # compiler invocations dumped to stdout
           jq -r '.[].command' ${GITHUB_WORKSPACE}/build/compile_commands.json

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:c-cpp"
