name: Static Analyzers

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    env:
      CMAKE_GENERATOR: Ninja
      CI_COMPILER: clang
      CI_LINKER: lld

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          source-root: source
          languages: c-cpp
          build-mode: manual
          queries: security-extended,security-and-quality

      - name: Configure
        run: |
          cmake \
              -S source \
              -B build \
              -DAUTOCOMPAT_ENABLE_TESTING=OFF

      - name: Build
        run: |
          cmake --build build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          checkout_path: ${{ github.workspace }}/source
          category: "/language:c-cpp"
          upload-database: true

  clang-analyzer:
    name: Clang Analyzer
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/chuckatkins/cuda-autocompat:ci-ubuntu-latest

    env:
      CMAKE_GENERATOR: Ninja
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Configure
        env:
          LAUNCHER_OVERRIDE_CC: ${{ env.CC }}
          LAUNCHER_OVERRIDE_CXX: ${{ env.CXX }}
        run: |
          scan-build cmake \
            -S source \
            -B build \
            -DAUTOCOMPAT_ENABLE_OVERRIDE_LAUNCHER=ON \
            -DBUILD_TESTING=OFF

      - name: Analyze
        env:
          CCC_CC: /bin/true
          CCC_CXX: /bin/true
        run: |
          mkdir sarif
          scan-build \
            -V -sarif -o sarif \
            cmake --build build

      - name: Merge SARIF results
        run: |
          jq -s '.[0] * {
              runs: (map(.runs) | add | map(
                .tool.driver.name = "Clang Static Analyzer"
              ))
            }' \
            sarif/*/*.sarif | tee merged.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          checkout_path: source
          sarif_file: merged.sarif
